# Generated by Django 3.2.9 on 2022-03-26 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 3, 26)),
        ),
        migrations.AddField(
            model_name='rented',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 3, 26)),
        ),
    ]
