# Generated by Django 3.2.9 on 2022-03-27 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_auto_20220326_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
        migrations.AddField(
            model_name='place',
            name='appartment_number',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='bloc',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='building_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='floor',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='garage',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='number',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='street',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='zip_code',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='type_of_place',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='rented',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 3, 27)),
        ),
        migrations.AlterField(
            model_name='rented',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 3, 27)),
        ),
    ]
