# Generated by Django 3.2.9 on 2022-03-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_auto_20220327_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='banheiro',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='cozinha',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='quartos',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='sala',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
