# Generated by Django 3.2.9 on 2022-03-28 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_auto_20220327_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='banheiro',
            new_name='bathrooms',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='quartos',
            new_name='bedrooms',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='cozinha',
            new_name='kitchens',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='sala',
            new_name='living_rooms',
        ),
        migrations.AlterField(
            model_name='rented',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 3, 28)),
        ),
        migrations.AlterField(
            model_name='rented',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 3, 28)),
        ),
    ]
